### PR TITLE
add useful stuff like lint-staged + .yarnrc + ...

### PR DESCRIPTION
**Pull request by majdi**

### CODE REVIEW

**Comment by Seedockh** [comment]
Thanks for this @majdi ! When running `yarn` in /client and /server, I've got a little issue related, I think, with the `.yarnrc` file : 
client-yarn

Do you think it's on your package side to be resolved ? Does it need any additionnal configuration to get rid of this `401 Unauthorized` ?

**Comment by majdi** [comment]
Got it, as the @mhirba package is hosted on Github. you have to generate a key to allow downloading.

Github > Settings Developer > settings then generate personal tokens with scopes that allow read on the package.

Finally, create on your laptop `~/.npmrc` with :
always-auth=true
//npm.pkg.github.com/:_authToken=XXX

That will allow you to use the package and all others public/private packages hosted on GitHub :)
Maybe it can be cool to add this to the **Readme** file.

**Comment by Seedockh** [comment]
Will do ASAP 👌

**Comment by Seedockh** [comment]
@majdi Almost there ! I'm well authorized, but I still got issues when running `yarn` : 
- client : ` Couldn't find package "@mhirba/eslint-config-base" on the "npm" registry.`
- server : ` Couldn't find package "@mhirba/babel-preset-next" on the "npm" registry.`

Did I miss something ?

**Comment by majdi** [comment]
Can you try to add a line `@mhirba:registry=https://npm.pkg.github.com` in your `~/.npmrc` file just after always-auth=true :)

**Comment by Seedockh** [comment]
Done @majdi ! After updating `Node ^13.11` and `Yarn ^1.22` ...

**Pull request merged**
